import numpy as np
import pandas as pd
import xlrd
import os
import openpyxl
from pathlib import Path


# Program Fitness Function
# Begin
# For h = 1 to h = 8760
#     Step 1: EV demand calculation
def Ev_Demand():
    pass


#         Generate random numbers
#         Obtain the arrival time of EV
#         Obtain the Kind of EV and battery capacity
#         Obtain the battery's SOC


#     Step 2: Renewable Energy calculation
#         Generate random numbers
#         Obtain the energy generated by wind generators.
#         Obtain the energy generated by solar modules
def solar_pv():
    pass
    # Glob_i = pd.read_excel('D:\\Python Coding\\Glob.xlsx',engine='openpyxl')
    # print(Glob_i)
    # area_pv = range(1, 1875)
    # eff_pv = 0.17
    # pv_power = Glob_i * area_pv * eff_pv
    # return pv_power

#     Step 3 : Energy balance
#         Calculate the energy flows among devices that meet the device's restrictions.
# End_for:
#     Step 4: Evaluation of the fitness function NPV.
# End
